services:
  wiremock:
    image: wiremock/wiremock:3.9.1
    container_name: wiremock
    restart: unless-stopped
    command: ["--global-response-templating", "--verbose"]
    volumes:
      - ./wiremock:/home/wiremock
    ports:
      - "8089:8080"
    networks: [santinet]

  toxiproxy:
    image: ghcr.io/shopify/toxiproxy:2.12.0
    container_name: toxiproxy
    restart: unless-stopped
    ports:
      - "8474:8474"
      - "8666:8666"
    networks: [santinet]

  k6:
    image: grafana/k6:0.52.0
    container_name: k6
    profiles: ["manual"]
    volumes:
      - ./k6:/scripts
    networks: [santinet]

networks:
  santinet:
    external: true
    name: santinet