services:
  postgres:
    image: postgres:13.12
    container_name: postgres
    restart: unless-stopped
    volumes:
      - ./postgres-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: d2b
    ports:
      - "5433:5432"

networks:
  default:
    external: true
    name: santinet